exclude: '^(data|prebuilt)'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: check-ast
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
      args: ["--remove"]
    - id: check-merge-conflict
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.4.0
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
