#!/usr/bin/env python
git_repos = [
  #["STATUS", "FAMILY-NAME", "GIT-REPO-URL", "FONTFILES-PREFIX"],
  ["OK", "ABeeZee", "https://github.com/googlefonts/abeezee.git", "fonts/ttf/ABeeZee-"],
  ["?", "abel", "", ""],
  ["?", "abhayalibre", "", ""],
  ["?", "abrilfatface", "", ""],
  ["?", "abyssinicasil", "", ""],
  ["?", "aclonica", "", ""],
  ["?", "acme", "", ""],
  ["?", "actor", "", ""],
  ["OK", "Adamina", "https://github.com/cyrealtype/Adamina.git", "fonts/Adamina-"],
  ["OK", "Abhaya Libre", "https://github.com/mooniak/abhaya-libre-font", "fonts/ttf/AbhayaLibre-"],
  ["OK", "Adobe Blank", "https://github.com/adobe-fonts/adobe-blank", "AdobeBlank"],
  ["?", "adventpro", "", ""],
  ["?", "aguafinascript", "", ""],
  ["?", "akronim", "", ""],
  ["?", "aksarabaligalang", "", ""],
  ["?", "aladin", "", ""],
  ["?", "aldrich", "", ""],
  ["?", "alef", "", ""],
  ["?", "alefhebrew", "", ""],
  ["?", "alegreya", "", ""],
  ["?", "alegreyasans", "", ""],
  ["?", "alegreyasanssc", "", ""],
  ["?", "alegreyasc", "", ""],
  ["?", "alexbrush", "", ""],
  ["?", "alfaslabone", "", ""],
  ["?", "alice", "", ""],
  ["OK", "Alike", "https://github.com/cyrealtype/Alike.git", "Alike-"],
  ["?", "alikeangular", "", ""],
  ["?", "allan", "", ""],
  ["?", "allerta", "", ""],
  ["?", "allertastencil", "", ""],
  ["?", "allura", "", ""],
  ["?", "almendra", "", ""],
  ["?", "almendradisplay", "", ""],
  ["?", "almendrasc", "", ""],
  ["?", "amarante", "", ""],
  ["?", "amaranth", "", ""],
  ["OK", "Amatic SC", "https://github.com/googlefonts/AmaticSC.git", "fonts/ttf/AmaticSC-"],
  ["?", "amethysta", "", ""],
  ["?", "amiri", "", ""],
  ["OK", "Amita", "https://github.com/etunni/Amita.git", "TTF/Amita-"],
  ["?", "amstelvaralpha", "", ""],
  ["OK", "Anaheim", "https://github.com/googlefonts/anaheimFont.git", "ttf/Anaheim-"],
  ["?", "andada", "", ""],
  ["?", "andadasc", "", ""],
  ["?", "andika", "", ""],
  ["?", "angkor", "", ""],
  ["?", "annieuseyourtelescope", "", ""],
  ["?", "anonymouspro", "", ""],
  ["?", "antic", "", ""],
  ["?", "anticdidone", "", ""],
  ["?", "anticslab", "", ""],
  ["OK", "Anton", "https://github.com/googlefonts/AntonFont.git", "fonts/Anton-"],
  ["?", "antonio", "", ""],
  ["?", "arapey", "", ""],
  ["?", "arbutus", "", ""],
  ["?", "arbutusslab", "", ""],
  ["?", "architectsdaughter", "", ""],
  ["?", "archivo", "", ""],
  ["?", "archivoblack", "", ""],
  ["?", "archivonarrow", "", ""],
  ["?", "arimo", "", ""],
  ["?", "arizonia", "", ""],
  ["?", "armata", "", ""],
  ["?", "arsenal", "", ""],
  ["?", "artifika", "", ""],
  ["?", "arvo", "", ""],
  ["OK", "Arya", "https://github.com/etunni/Arya.git", "TTF/Arya-"],
  ["OK", "Asap", "https://github.com/googlefonts/Asap.git", "Fonts/Asap-"],
  ["?", "asapcondensed", "", ""],
  ["OK", "Asar", "https://github.com/EbenSorkin/Asar.git", "Asar-"],
  ["?", "asset", "", ""],
  ["?", "astloch", "", ""],
  ["?", "asul", "", ""],
  ["OK", "Atomic Age", "https://github.com/EbenSorkin/Atomic-Age.git", "fonts/ttf/AtomicAge-"],
  ["?", "aubrey", "", ""],
  ["?", "audiowide", "", ""],
  ["?", "autourone", "", ""],
  ["?", "average", "", ""],
  ["?", "averagesans", "", ""],
  ["?", "averiagruesalibre", "", ""],
  ["?", "averialibre", "", ""],
  ["?", "averiasanslibre", "", ""],
  ["?", "averiaseriflibre", "", ""],
  ["?", "badscript", "", ""],
  ["?", "bahiana", "", ""],
  ["TTX", "Baloo", "https://github.com/girish-dalvi/Baloo", "TTX/Baloo-"],
  ["TTX", "BalooBhai", "https://github.com/girish-dalvi/Baloo", "TTX/BalooBhai-"],
  ["TTX", "BalooBhaijaan", "https://github.com/girish-dalvi/Baloo", "TTX/BalooBhaijaan-"],
  ["TTX", "BalooBhaina", "https://github.com/girish-dalvi/Baloo", "TTX/BalooBhaina-"],
  ["TTX", "BalooChettan", "https://github.com/girish-dalvi/Baloo", "TTX/BalooChettan-"],
  ["TTX", "BalooDa", "https://github.com/girish-dalvi/Baloo", "TTX/BalooDa-"],
  ["TTX", "BalooPaaji", "https://github.com/girish-dalvi/Baloo", "TTX/BalooPaaji-"],
  ["TTX", "BalooTamma", "https://github.com/girish-dalvi/Baloo", "TTX/BalooTamma-"],
  ["TTX", "BalooTammudu", "https://github.com/girish-dalvi/Baloo", "TTX/BalooTammudu-"],
  ["TTX", "BalooThambi", "https://github.com/girish-dalvi/Baloo", "TTX/BalooThambi-"],
  ["?", "balthazar", "", ""],
  ["OK", "Bangers", "https://github.com/googlefonts/bangers.git", "fonts/Bangers-"],
  ["?", "barrio", "", ""],
  ["OK", "Basic", "https://github.com/EbenSorkin/Basic.git", "Basic-"],
  ["?", "battambang", "", ""],
  ["?", "baumans", "", ""],
  ["?", "bayon", "", ""],
  ["?", "belgrano", "", ""],
  ["?", "belleza", "", ""],
  ["?", "benchnine", "", ""],
  ["?", "bentham", "", ""],
  ["?", "berkshireswash", "", ""],
  ["OK", "Bevan", "https://github.com/googlefonts/BevanFont.git", "ttf/Bevan-"],
  ["OK", "Bhavuka", "https://github.com/10four/Bhavuka.git", "Bhavuka-"],
  ["?", "bigelowrules", "", ""],
  ["?", "bigshotone", "", ""],
  ["?", "bilbo", "", ""],
  ["?", "bilboswashcaps", "", ""],
  ["NOTE", "Biryani", "https://github.com/typeoff/biryani", "Font Files/TTFs with ttautohints/Biryani-"],
  # Note: There's also Biryani without autohints.
  ["?", "bitter", "", ""],
  ["?", "blackopsone", "", ""],
  ["?", "bokor", "", ""],
  ["?", "bonbon", "", ""],
  ["?", "boogaloo", "", ""],
  ["?", "bowlbyone", "", ""],
  ["?", "bowlbyonesc", "", ""],
  ["?", "brawler", "", ""],
  ["?", "breeserif", "", ""],
  ["?", "brunoace", "", ""],
  ["?", "brunoacesc", "", ""],
  ["?", "bubblegumsans", "", ""],
  ["?", "bubblerone", "", ""],
  ["?", "buda", "", ""],
  ["?", "buenard", "", ""],
  ["?", "butcherman", "", ""],
  ["?", "butchermancaps", "", ""],
  ["?", "butterflykids", "", ""],
  ["OK", "Cabin", "https://github.com/impallari/Cabin.git", "fonts/TTF/Cabin-"],
  ["?", "cabincondensed", "", ""],
  ["?", "cabinsketch", "", ""],
  ["?", "cabinvfbeta", "", ""],
  ["?", "caesardressing", "", ""],
  ["?", "cagliostro", "", ""],
  ["?", "calligraffitti", "", ""],
  ["OK", "Cambay", "https://github.com/anexasajoop/cambay.git", "cambay/Font files/Unhinted/CambayDevanagari-"],
  ["?", "cambo", "", ""],
  ["?", "candal", "", ""],
  ["?", "cantarell", "", ""],
  ["?", "cantataone", "", ""],
  ["?", "cantoraone", "", ""],
  ["?", "capriola", "", ""],
  ["?", "cardo", "", ""],
  ["?", "carme", "", ""],
  ["?", "carroisgothic", "", ""],
  ["?", "carroisgothicsc", "", ""],
  ["?", "carterone", "", ""],
  ["?", "catamaran", "", ""],
  ["OK", "Catamaran Tamil", "https://github.com/VanillaandCream/Catamaran", "Fonts/Catamaran-"],
  ["?", "caudex", "", ""],
  ["?", "caveat", "", ""], # I laughed at this: "There are a few more caveats [...]" https://github.com/googlefonts/caveat.git
  ["?", "caveatbrush", "", ""],
  ["?", "cedarvillecursive", "", ""],
  ["?", "cevicheone", "", ""],
  ["?", "changa", "", ""],
  ["?", "changaone", "", ""],
  ["?", "chango", "", ""],
  ["?", "chauphilomeneone", "", ""],
  ["?", "chelaone", "", ""],
  ["?", "chelseamarket", "", ""],
  ["?", "chenla", "", ""],
  ["?", "cherrycreamsoda", "", ""],
  ["?", "cherryswash", "", ""],
  ["?", "chewy", "", ""],
  ["?", "chicle", "", ""],
  ["?", "chivo", "", ""],
  ["OK", "Chonburi", "https://github.com/cadsondemak/chonburi.git", "fonts/Chonburi-"],
  ["?", "cinzel", "", ""],
  ["?", "cinzeldecorative", "", ""],
  ["?", "clara", "", ""],
  ["?", "clickerscript", "", ""],
  ["NOTE", "Coda", "https://github.com/vernnobile/CodaFont", "coda/in-progress/Regular/Coda"], # BAD REPO!
  # Note: Coda's repo has a bad tree structure (one weight per folder). There's also a "Heavy".
  ["?", "codacaption", "", ""],
  ["?", "codystar", "", ""],
  ["?", "combo", "", ""],
  ["?", "comfortaa", "", ""],
  ["?", "comingsoon", "", ""],
  ["?", "concertone", "", ""],
  ["?", "condiment", "", ""],
  ["?", "content", "", ""],
  ["?", "contrailone", "", ""],
  ["?", "convergence", "", ""],
  ["?", "cookie", "", ""],
  ["?", "copse", "", ""],
  ["?", "corben", "", ""],
  ["OK", "Cormorant", "https://github.com/CatharsisFonts/Cormorant.git", "1. TrueType Font Files/Cormorant-"],
  ["?", "cormorantgaramond", "", ""],
  ["?", "cormorantinfant", "", ""],
  ["?", "cormorantsc", "", ""],
  ["?", "cormorantunicase", "", ""],
  ["?", "cormorantupright", "", ""],
  ["?", "courgette", "", ""],
  ["?", "cousine", "", ""],
  ["?", "coustard", "", ""],
  ["?", "coveredbyyourgrace", "", ""],
  ["?", "craftygirls", "", ""],
  ["?", "creepster", "", ""],
  ["?", "creepstercaps", "", ""],
  ["?", "creteround", "", ""],
  ["?", "crimsontext", "", ""],
  ["?", "croissantone", "", ""],
  ["?", "crushed", "", ""],
  ["?", "cuprum", "", ""],
  ["?", "cutive", "", ""],
  ["NOTE", "Cutive Mono", "https://github.com/googlefonts/CutiveFont.git", "fonts/CutiveMono-"],
  # Note: There's also an old Cultive Roman on the upstream repo at: https://github.com/vernnobile/CutiveFont/tree/master/CutiveRoman
  ["?", "cwtexfangsong", "", ""],
  ["?", "cwtexhei", "", ""],
  ["?", "cwtexkai", "", ""],
  ["?", "cwtexming", "", ""],
  ["?", "cwtexyen", "", ""],
  ["?", "damion", "", ""],
  ["?", "dancingscript", "", ""],
  ["?", "dangrek", "", ""],
  ["?", "dawningofanewday", "", ""],
  ["?", "daysone", "", ""],
##### Not on GFonts: ["OTF", "Datalegreya", "https://github.com/figs-lab/datalegreya", ""], # sources with OTF binaries, but no TTFs.
  ["OK", "Dekko", "https://github.com/EbenSorkin/Dekko.git", "Dekko-"],
  ["?", "delius", "", ""],
  ["?", "deliusswashcaps", "", ""],
  ["?", "deliusunicase", "", ""],
  ["?", "dellarespira", "", ""],
  ["?", "denkone", "", ""],
  ["?", "devonshire", "", ""],
  ["UFO", "Dhurjati", "https://github.com/appajid/dhurjati", "Dhurjati"],
  ["NOTE", "Dhyana", "https://github.com/vernnobile/DhyanaFont", "Regular/Dhyana"], # BAD REPO!
  # Note: Dhyana's repo has a bad tree structure (one weight per folder). There's also a "Bold".
  ["?", "didactgothic", "", ""],
  ["GH-PAGES", "Digital Numbers", "https://github.com/s-a/digital-numbers-font", "gh-pages/dist/DigitalNumbers-"],
  # Note: The above requires adding to FB support for cloning a repo from a different branch (such as gh-pages)
  ["OK", "Dinah", "https://github.com/elms-/Dinah", "DINAHv1.3/DINAH"], # BAD REPO: NON-CANONICAL NAMES!
  ["?", "diplomata", "", ""],
  ["?", "diplomatasc", "", ""],
  ["?", "domine", "", ""],
  ["?", "donegalone", "", ""],
  ["?", "doppioone", "", ""],
  ["?", "dorsa", "", ""],
  ["?", "dosis", "", ""],
  ["?", "droidarabickufi", "", ""],
  ["?", "droidarabicnaskh", "", ""],
  ["?", "droidsans", "", ""],
  ["?", "droidsansethiopic", "", ""],
  ["?", "droidsansjapanese", "", ""],
  ["?", "droidsansmono", "", ""],
  ["?", "droidsanstamil", "", ""],
  ["?", "droidsansthai", "", ""],
  ["?", "droidserif", "", ""],
  ["?", "droidserifthai", "", ""],
  ["?", "drsugiyama", "", ""],
  ["?", "durusans", "", ""],
  ["?", "dynalight", "", ""],
  ["?", "eaglelake", "", ""],
  ["?", "eater", "", ""],
  ["?", "eatercaps", "", ""],
  ["?", "ebgaramond", "", ""],
  ["?", "economica", "", ""],
  ["TTX", "Eczar", "https://github.com/rosettatype/Eczar", "fonts/ttf/Eczar-"],
  ["OK", "Ek-Mukta", "https://github.com/googlefonts/MuktaGFVersion.git", "fonts/EkMukta-"],
  ["OK", "Ek-Mukta Mukta Devanagari", "https://github.com/googlefonts/MuktaGFVersion.git", "fonts/Mukta-"],
  ["OK", "Ek-Mukta MuktaMalar Tamil", "https://github.com/googlefonts/MuktaGFVersion.git", "fonts/MuktaMalar-"],
  ["OK", "Ek-Mukta MuktaVaani Gujarati", "https://github.com/googlefonts/MuktaGFVersion.git", "fonts/MuktaVaani-"],
  ["?", "electrolize", "", ""],
  ["?", "elsie", "", ""],
  ["?", "elsieswashcaps", "", ""],
  ["?", "emblemaone", "", ""],
  ["?", "emilyscandy", "", ""],
  ["?", "encodesans", "", ""],
  ["?", "encodesanscompressed", "", ""],
  ["?", "encodesanscondensed", "", ""],
  ["?", "encodesansexpanded", "", ""],
  ["?", "encodesansnarrow", "", ""],
  ["?", "encodesanssemicondensed", "", ""],
  ["?", "encodesanssemiexpanded", "", ""],
  ["?", "encodesansvfbeta", "", ""],
  ["?", "encodesanswide", "", ""],
  ["?", "engagement", "", ""],
  ["?", "englebert", "", ""],
  ["?", "enriqueta", "", ""],
  ["?", "ericaone", "", ""],
  ["?", "esteban", "", ""],
  ["?", "euphoriascript", "", ""],
  ["?", "ewert", "", ""],
  ["?", "exo", "", ""],
  ["?", "exo2", "", ""],
  ["?", "expletussans", "", ""],
  ["?", "fanwoodtext", "", ""],
  ["?", "fascinate", "", ""],
  ["?", "fascinateinline", "", ""],
  ["?", "fasterone", "", ""],
  ["?", "fasthand", "", ""],
  ["?", "faunaone", "", ""],
  ["?", "faustina", "", ""],
  ["OK", "Federant", "https://github.com/cyrealtype/Federant.git", "Federant-"],
  ["?", "federo", "", ""],
  ["?", "felipa", "", ""],
  ["?", "fenix", "", ""],
  ["?", "fingerpaint", "", ""],
  ## ["NOTE", "Fira", "https://github.com/mozilla/Fira", "ttf/FiraSans-"],
  # Note: The above has got good names, but also some extra like "FiraSans-BookItalic.ttf"
  #       (may be treated as a separate family?)
  # Note2: The upstream version (commented out repo above) seems to be updated more frequently,
  #        but does not fit Google Fonts naming scheme, so we'll run checks on each individual
  #        family form the Google Fonts version available on the repos below:
  ["OK", "FiraCode", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraCode-"],
  ["OK", "FiraMono", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraMono-"],
  ["OK", "FiraSans", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraSans-"],
  ["OK", "FiraSansCondensed", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraSansCondensed-"],
  ["OK", "FiraSansCondensedHairline", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraSansCondensedHairline-"],
  ["OK", "FiraSansExtraCondensed", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraSansExtraCondensed-"],
  ["OK", "FiraSansExtraCondensedHairline", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraSansExtraCondensedHairline-"],
  ["OK", "FiraSansHairline", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraSansHairline-"],
  ["OK", "FiraSansUltra", "https://github.com/googlefonts/FiraGFVersion.git", "fonts/FiraSansUltra-"],
  ["?", "fjallaone", "", ""],
  ["?", "fjordone", "", ""],
  ["?", "flamenco", "", ""],
  ["?", "flavors", "", ""],
  ["?", "fondamento", "", ""],
  ["?", "fontdinerswanky", "", ""],
  ["?", "forum", "", ""],
  ["OK", "Francois One", "https://github.com/googlefonts/francoisoneFont.git", "fonts/FrancoisOne-"],
  ["?", "freckleface", "", ""],
  ["?", "frederickathegreat", "", ""],
  ["?", "fredokaone", "", ""],
  ["?", "freehand", "", ""],
  ["?", "fresca", "", ""],
  ["?", "frijole", "", ""],
  ["TTX", "Fruktur", "https://github.com/EbenSorkin/Fruktur", "TTX/TTF/Fruktur-"],
  ["?", "fugazone", "", ""],
  ["?", "gabriela", "", ""],
  ["?", "gafata", "", ""],
  ["?", "galdeano", "", ""],
  ["?", "galindo", "", ""],
  ["?", "gemunulibre", "", ""],
  ["?", "gentiumbasic", "", ""],
  ["?", "gentiumbookbasic", "", ""],
  ["?", "geo", "", ""],
  ["?", "geostar", "", ""],
  ["?", "geostarfill", "", ""],
  ["?", "germaniaone", "", ""],
  ["?", "gfsdidot", "", ""],
  ["?", "gfsneohellenic", "", ""],
  ["?", "ghub_fontrepos.txt", "", ""],
  ["UFO", "Gidugu", "https://github.com/appajid/gidugu", "Gidugu"],
  ["?", "gildadisplay", "", ""],
  ["?", "giveyouglory", "", ""],
  ["?", "glassantiqua", "", ""],
  ["OK", "Glegoo", "https://github.com/etunni/glegoo.git", "Glegoo-"],
  ["?", "gloriahallelujah", "", ""],
  ["TTX", "Goblin One", "", "GoblinOne"],
  ["?", "gochihand", "", ""],
  ["?", "gorditas", "", ""],
  ["?", "goudybookletter1911", "", ""],
  ["?", "graduate", "", ""],
  ["?", "grandhotel", "", ""],
  ["?", "gravitasone", "", ""],
  ["?", "greatvibes", "", ""],
  ["?", "griffy", "", ""],
  ["?", "gruppo", "", ""],
  ["?", "gudea", "", ""],
  ["OTF", "Gurajada", "https://github.com/appajid/gurajada", ""],
  ["?", "habibi", "", ""],
  ["?", "halant", "", ""],
  ["?", "hammersmithone", "", ""],
  ["?", "hanalei", "", ""],
  ["?", "hanaleifill", "", ""],
  ["?", "handlee", "", ""],
  ["?", "hanna", "", ""],
  ["?", "hannari", "", ""],
  ["?", "hanuman", "", ""],
  ["TTX", "happymonkey", "https://github.com/librefonts/happymonkey", "HappyMonkey-"],
  ["?", "headlandone", "", ""],
  ["?", "hennypenny", "", ""],
  ["?", "hermeneusone", "", ""],
  ["?", "herrvonmuellerhoff", "", ""],
  ["?", "hind", "", ""],
  ["OTF", "Hind Colombo", "https://github.com/itfoundry/hind-colombo", "build/HindColombo-"], # sources with OTF binaries, but no TTFs.
  ["OTF", "Hind Guntur", "https://github.com/itfoundry/hind-guntur", "build/HindGuntur-"], # sources with OTF binaries, but no TTFs.
  ["OTF", "Hind Jalandhar", "https://github.com/itfoundry/hind-jalandhar", "build/HindJalandhar-"], # sources with OTF binaries, but no TTFs.
  ["OTF", "Hind Kochi", "https://github.com/itfoundry/hind-kochi", "build/HindKochi-"], # sources with OTF binaries, but no TTFs.
  ["OTF", "Hind Madurai", "https://github.com/itfoundry/hind-madurai", "build/HindMadurai-"], # sources with OTF binaries, but no TTFs.
  ["OTF", "Hind Mysuru", "https://github.com/itfoundry/hind-mysuru", "build/HindMysuru-"], # sources with OTF binaries, but no TTFs.
  ["OTF", "Hind Siliguri", "https://github.com/itfoundry/hind-siliguri", "build/HindSiliguri-"], # sources with OTF binaries, but no TTFs.
  ["OTF", "Hind Vadodara", "https://github.com/itfoundry/hind-vadodara", "build/HindVadodara-"], # sources with OTF binaries, but no TTFs.
  ["?", "holtwoodonesc", "", ""],
  ["?", "homemadeapple", "", ""],
  ["OK", "Homenaje", "https://github.com/googlefonts/Homenaje.git", "fonts/Homenaje-"],
  ["?", "iceberg", "", ""],
  ["?", "iceland", "", ""],
  ["?", "imfelldoublepica", "", ""],
  ["?", "imfelldoublepicasc", "", ""],
  ["?", "imfelldwpica", "", ""],
  ["?", "imfelldwpicasc", "", ""],
  ["?", "imfellenglish", "", ""],
  ["?", "imfellenglishsc", "", ""],
  ["?", "imfellfrenchcanon", "", ""],
  ["?", "imfellfrenchcanonsc", "", ""],
  ["?", "imfellgreatprimer", "", ""],
  ["?", "imfellgreatprimersc", "", ""],
  ["?", "imprima", "", ""],
  ["GFONTS-REPO", "Inconsolata", "https://github.com/google/fonts/tree/master/ofl/inconsolata", "ofl/inconsolata/Inconsolata-"], # too large to checkout!
  ["?", "inder", "", ""],
  ["OK", "Indie Flower", "https://github.com/googlefonts/indieflower.git", "fonts/IndieFlower-"],
  ["?", "inika", "", ""],
  ["OK", "Inknut Antiqua", "https://github.com/clauseggers/Inknut-Antiqua.git", "TTF-OTF/InknutAntiqua-"],
  ["?", "irishgrover", "", ""],
  ["?", "irishgrowler", "", ""],
  ["?", "istokweb", "", ""],
  ["?", "italiana", "", ""],
  ["?", "italianno", "", ""],
  ["OK", "Itim", "https://github.com/cadsondemak/itim.git", "fonts/Itim-"],
  ["?", "jacquesfrancois", "", ""],
  ["?", "jacquesfrancoisshadow", "", ""],
  ["GH-PAGES", "Jaldi", "https://github.com/Omnibus-Type/Jaldi", "gh-pages/Fonts/Jaldi-"], # add support for gh-pages branch on fontbakery!
  ["?", "jejugothic", "", ""],
  ["?", "jejuhallasan", "", ""],
  ["?", "jejumyeongjo", "", ""],
  ["?", "jimnightshade", "", ""],
  ["?", "jockeyone", "", ""],
  ["?", "jollylodger", "", ""],
  ["?", "jomolhari", "", ""],
  ["?", "josefinsans", "", ""],
  ["?", "josefinsansstdlight", "", ""],
  ["?", "josefinslab", "", ""],
  ["?", "jotione", "", ""],
  ["?", "jsmathcmbx10", "", ""],
  ["?", "jsmathcmex10", "", ""],
  ["?", "jsmathcmmi10", "", ""],
  ["?", "jsmathcmr10", "", ""],
  ["?", "jsmathcmsy10", "", ""],
  ["?", "jsmathcmti10", "", ""],
  ["?", "judson", "", ""],
  ["?", "julee", "", ""],
  ["?", "juliussansone", "", ""],
  ["?", "junge", "", ""],
  ["NOTE", "Jura", "https://github.com/ossobuffo/jura", "fonts/ttf/Jura-"],
  # Note: This seems to be the upstream repo, even though there's some work being done towards merging a large pull request at https://github.com/googlefonts/jura/pull/2
  ["?", "justanotherhand", "", ""],
  ["?", "justmeagaindownhere", "", ""],
  ["NOTE", "Kadwa", "https://github.com/solmatas/Kadwa", "Kadwa Font Files/Kadwa-"],
  # Note: There's also a "Kadwa Cyrillic" in this repo, but only Glyphs source files. No TTF binaries.
  ["OTF", "Kalam", "https://github.com/itfoundry/kalam", "build/Kalam-"], # sources with OTF binaries, but no TTFs.
  ["?", "kameron", "", ""],
  ["OK", "Kanit", "https://github.com/cadsondemak/kanit.git", "font/Kanit-"],
  ["?", "kantumruy", "", ""],
  ["?", "karla", "", ""],
  ["?", "karlatamilinclined", "", ""],
  ["?", "karlatamilupright", "", ""],
  ["?", "karma", "", ""],
  ["?", "kaushanscript", "", ""],
  ["OK", "Kavoon", "https://github.com/EbenSorkin/Kavoon.git", "Kavoon-"],
  ["?", "kdamthmor", "", ""],
  ["?", "keaniaone", "", ""],
  ["?", "kellyslab", "", ""],
  ["?", "kenia", "", ""],
  ["OTF", "Khand", "https://github.com/itfoundry/khand", "build/Khand-"], # sources with OTF binaries, but no TTFs.
  ["?", "khmer", "", ""],
  ["OK", "Khula", "https://github.com/erinmclaughlin/Khula.git", "ttf_hinted/Khula-"],
  ["?", "khyay", "", ""],
  ["?", "kiteone", "", ""],
  ["?", "knewave", "", ""],
  ["?", "kokoro", "", ""],
  ["?", "kopubbatang", "", ""],
  ["?", "kottaone", "", ""],
  ["?", "koulen", "", ""],
  ["?", "kranky", "", ""],
  ["?", "kreon", "", ""],
  ["?", "kristi", "", ""],
  ["?", "kronaone", "", ""],
  ["OK", "Kurale", "https://github.com/etunni/kurale.git", "fonts/Kurale-"],
  ["?", "labelleaurore", "", ""],
  ["?", "laila", "", ""],
  ["?", "lakkireddy", "", ""],
  ["?", "lancelot", "", ""],
  ["?", "laomuangdon", "", ""],
  ["?", "laomuangkhong", "", ""],
  ["?", "laosanspro", "", ""],
  ["?", "lateef", "", ""],
  ["OK", "Lato", "https://github.com/googlefonts/LatoGFVersion.git", "fonts/Lato-"],
  ##### Not on GFonts: ["UFO", "Lakkireddy", "https://github.com/appajid/lakkireddy", "LakkiReddy"],
  ["?", "leaguescript", "", ""],
  ["?", "leckerlione", "", ""],
  ["?", "ledger", "", ""],
  ["?", "lekton", "", ""],
  ["?", "lemon", "", ""],
  ["?", "librebaskerville", "", ""],
  ["?", "librecaslontext", "", ""],
  ["?", "lifesavers", "", ""],
  ["?", "lilitaone", "", ""],
  ["?", "lilyscriptone", "", ""],
  ["?", "limelight", "", ""],
  ["?", "lindenhill", "", ""],
  ["?", "lobster", "", ""],
  ["?", "lobstertwo", "", ""],
  ["?", "lohitbengali", "", ""],
  ["?", "lohitdevanagari", "", ""],
  ["?", "lohittamil", "", ""],
  ["?", "londrinaoutline", "", ""],
  ["?", "londrinashadow", "", ""],
  ["?", "londrinasketch", "", ""],
  ["?", "londrinasolid", "", ""],
  ["?", "lora", "", ""],
  ["?", "lovedbytheking", "", ""],
  ["?", "loversquarrel", "", ""],
  ["?", "loveyalikeasister", "", ""],
  ["?", "luckiestguy", "", ""],
  ["?", "lusitana", "", ""],
  ["?", "lustria", "", ""],
  ["?", "macondo", "", ""],
  ["?", "macondoswashcaps", "", ""],
  ["?", "magra", "", ""],
  ["?", "maidenorange", "", ""],
  ["?", "mako", "", ""],
  ["UFO", "Mallanna", "https://github.com/appajid/mallanna", "Mallanna"],
  ["UFO", "Mandali", "https://github.com/appajid/mandali", "Mandali"],
  ["?", "manuale", "", ""],
  ["?", "marcellus", "", ""],
  ["?", "marcellussc", "", ""],
  ["?", "marckscript", "", ""],
  ["?", "margarine", "", ""],
  ["?", "markoone", "", ""],
  ["?", "marmelad", "", ""],
  ["NOTE", "Martel", "https://github.com/typeoff/martel", "Martel Font Files/TTFs with ttfautohints/Martel-"],
  # Note: There's also a "Martel" family without autohints at this repo.
  ["NOTE", "Martel Sans", "https://github.com/typeoff/martel_sans", "Martel Sans Font Files/TTFs with ttautohints/MartelSans-"],
  # Note: There's also a "Martel Sans" family without autohints at this repo.
  ["?", "marvel", "", ""],
  ["?", "mate", "", ""],
  ["?", "matesc", "", ""],
  ["OK", "Maven Pro", "https://github.com/googlefonts/mavenproFont.git", "fonts/MavenPro-"],
  ["?", "mavenprovfbeta", "", ""],
  ["?", "mclaren", "", ""],
  ["?", "meddon", "", ""],
  ["?", "medievalsharp", "", ""],
  ["?", "medulaone", "", ""],
  ["?", "megrim", "", ""],
  ["?", "meiescript", "", ""],
  ["?", "mergeone", "", ""],
  ["?", "merienda", "", ""],
  ["?", "meriendaone", "", ""],
  ["?", "merriweather", "", ""],
  ["UFO", "Merriweather Sans", "https://github.com/EbenSorkin/Merriweather-Sans", "SRC/MerriweatherSans-"],
  ["?", "mervalescript", "", ""],
  ["?", "metal", "", ""],
  ["?", "metalmania", "", ""],
  ["?", "metamorphous", "", ""],
  ["OK", "Metrophobic", "https://github.com/googlefonts/MetrophobicFont.git", "fonts/Metrophobic-"],
  ["?", "miama", "", ""],
  ["?", "michroma", "", ""],
  ["?", "milonga", "", ""],
  ["?", "miltonian", "", ""],
  ["?", "miltoniantattoo", "", ""],
  ["?", "mina", "", ""],
  ["?", "miniver", "", ""],
  ["?", "missfajardose", "", ""],
  ["?", "misssaintdelafield", "", ""],
  ["TTX", "Modak", "https://github.com/girish-dalvi/Modak", "TTX/Modak-"],
  ["?", "modernantiqua", "", ""],
  ["SOURCE-ONLY", "Molengo", "https://github.com/googlefonts/molengo-fonts.git", "sfd/Molengo-"],
  ["?", "molle", "", ""],
  ["UFO", "Monda", "https://github.com/vernnobile/mondaFont", "in-progress/Roman/Monda-"], #BAD REPO
  # Note: In the above repo there are versions 1.00, 2.0 and in-progress
  ["?", "monofett", "", ""],
  ["?", "monoton", "", ""],
  ["?", "monsieurladoulaise", "", ""],
  ["?", "montaga", "", ""],
  ["?", "montez", "", ""],
  ["?", "montserrat", "", ""],
  ["?", "montserratalternates", "", ""],
  ["?", "montserratsubrayada", "", ""],
  ["?", "moul", "", ""],
  ["?", "moulpali", "", ""],
  ["?", "mountainsofchristmas", "", ""],
  ["?", "mousememoirs", "", ""],
  ["?", "mplus1p", "", ""],
  ["?", "mrbedford", "", ""],
  ["?", "mrbedfort", "", ""],
  ["?", "mrdafoe", "", ""],
  ["?", "mrdehaviland", "", ""],
  ["?", "mrssaintdelafield", "", ""],
  ["?", "mrssheppards", "", ""],
  ["?", "mukta", "", ""],
  ["?", "muktamalar", "", ""],
  ["?", "muktavaani", "", ""],
  ["OK", "Muli", "https://github.com/googlefonts/MuliFont.git", "fonts/Muli-"],
  ["?", "myanmarsanspro", "", ""],
  ["?", "mysteryquest", "", ""],
  ["?", "nanumbrushscript", "", ""],
  ["?", "nanumgothic", "", ""],
  ["?", "nanumgothiccoding", "", ""],
  ["?", "nanummyeongjo", "", ""],
  ["?", "nanumpenscript", "", ""],
  ["UFO", "Nats", "https://github.com/appajid/nats", "NATS"],
  ["?", "neucha", "", ""],
  ["?", "neuton", "", ""],
  ["?", "newrocker", "", ""],
  ["?", "newscycle", "", ""],
  ["?", "nicomoji", "", ""],
  ["?", "niconne", "", ""],
  ["?", "nikukyu", "", ""],
  ["?", "nixieone", "", ""],
  ["?", "nobile", "", ""],
  ["?", "nokora", "", ""],
  ["?", "norican", "", ""],
  ["?", "nosifer", "", ""],
  ["?", "nosifercaps", "", ""],
  ["?", "nothingyoucoulddo", "", ""],
  ["?", "noticiatext", "", ""],
  ["?", "notosans", "", ""],
  ["?", "notoserif", "", ""],
  ["?", "novacut", "", ""],
  ["?", "novaflat", "", ""],
  ["?", "novamono", "", ""],
  ["?", "novaoval", "", ""],
  ["?", "novaround", "", ""],
  ["?", "novascript", "", ""],
  ["?", "novaslim", "", ""],
  ["?", "novasquare", "", ""],
  ["UFO", "Ntr", "https://github.com/appajid/ntr", "NTR"],
  ["?", "numans", "", ""],
  ["NOTE", "Nunito", "https://github.com/googlefonts/NunitoFont.git", "fonts/Nunito-"],
  # There's also a "NunitoHeavy" family in the above repo.
  ["?", "nunitosans", "", ""],
  ["?", "nunitosansvfbeta", "", ""],
  ["?", "nunitovfbeta", "", ""],
  ["?", "odormeanchey", "", ""],
  ["?", "offside", "", ""],
  ["?", "oflsortsmillgoudytt", "", ""],
  ["?", "oldenburg", "", ""],
  ["?", "oldstandardtt", "", ""],
  ["?", "oleoscript", "", ""],
  ["?", "oleoscriptswashcaps", "", ""],
  ["?", "opensans", "", ""],
  ["?", "opensanscondensed", "", ""],
  ["?", "opensanshebrew", "", ""],
  ["?", "opensanshebrewcondensed", "", ""],
  ["?", "oranienbaum", "", ""],
  ["?", "orbitron", "", ""],
  ["?", "oregano", "", ""],
  ["?", "orienta", "", ""],
  ["?", "originalsurfer", "", ""],
  ["OK", "Oswald", "https://github.com/googlefonts/OswaldFont.git", "fonts/ttf/Oswald-"],
  ["?", "oswaldvfbeta", "", ""],
  ["?", "overlock", "", ""],
  ["?", "overlocksc", "", ""],
  ["NOTE", "Overpass", "https://github.com/googlefonts/overpass.git", "Webfonts/Overpass-Bold-"],
  # Note: There's also: "Desktop Fonts/Overpass-"
  ["?", "overpassmono", "", ""],
  ["?", "overpassvfbeta", "", ""],
  ["?", "overtherainbow", "", ""],
  ["?", "ovo", "", ""],
  ["?", "oxygen", "", ""],
  ["?", "oxygenmono", "", ""],
  ["?", "pacifico", "", ""],
  ["SOURCE-ONLY", "Padauk", "https://github.com/silnrsi/font-padauk", "font-source"],
  ["OK", "Palanquin", "https://github.com/VanillaandCream/Palanquin", "Palanquin/Palanquin/Palanquin-"],
  ["OK", "Palanquin Dark", "https://github.com/VanillaandCream/Palanquin", "PalanquinDark/Palanquin_Dark/PalanquinDark-"],
  ["OK", "Pangolin Sans", "https://github.com/googlefonts/pangolin.git", "fonts/Pangolin-"],
  ["?", "paprika", "", ""],
  ["?", "parisienne", "", ""],
  ["?", "passeroone", "", ""],
  ["?", "passionone", "", ""],
  ["?", "pathwaygothicone", "", ""],
  ["?", "patrickhand", "", ""],
  ["?", "patrickhandsc", "", ""],
  ["?", "patuaone", "", ""],
  ["?", "paytoneone", "", ""],
  ["?", "pecita", "", ""],
  ["UFO", "Peddana", "https://github.com/appajid/peddana", "Peddana-"],
  ["?", "peralta", "", ""],
  ["?", "permanentmarker", "", ""],
  ["?", "petitformalscript", "", ""],
  ["?", "petrona", "", ""],
  ["?", "phetsarath", "", ""],
  ["?", "philosopher", "", ""],
  ["?", "piedra", "", ""],
  ["?", "pinyonscript", "", ""],
  ["?", "pirataone", "", ""],
  ["?", "plaster", "", ""],
  ["?", "play", "", ""],
  ["?", "playball", "", ""],
  ["?", "playfairdisplay", "", ""],
  ["?", "playfairdisplaysc", "", ""],
  ["?", "podkova", "", ""],
  ["?", "poetsenone", "", ""],
  ["OK", "Poiret One", "https://github.com/alexeiva/poiretone.git", "fonts/ttf/PoiretOne-"],
  ["?", "pollerone", "", ""],
  ["?", "poly", "", ""],
  ["?", "pompiere", "", ""],
  ["UFO", "Ponnala", "https://github.com/appajid/ponnala", "Ponnala"],
  ["?", "pontanosans", "", ""],
  ["OTF", "Poppins", "https://github.com/itfoundry/poppins", "products/Poppins-"], # sources with OTF binaries, but no TTFs.
  ["?", "portersansblock", "", ""],
  ["?", "portlligatsans", "", ""],
  ["?", "portlligatslab", "", ""],
  ["?", "postnobillscolombo", "", ""],
  ["?", "postnobillsjaffna", "", ""],
  ["OK", "Pragati Narrow", "https://github.com/Omnibus-Type/PragatiNarrow", "Fonts/PragatiNarrow-"],
  ["?", "prata", "", ""],
  ["?", "preahvihear", "", ""],
  ["?", "pressstart2p", "", ""],
  ["?", "princesssofia", "", ""],
  ["?", "prociono", "", ""],
  ["?", "prostoone", "", ""],
  ["?", "ptmono", "", ""],
  ["?", "ptsans", "", ""],
  ["?", "ptsanscaption", "", ""],
  ["?", "ptsansnarrow", "", ""],
  ["?", "ptserif", "", ""],
  ["?", "ptserifcaption", "", ""],
  ["?", "puritan", "", ""],
  ["?", "purplepurse", "", ""],
  ["?", "quando", "", ""],
  ["?", "quantico", "", ""],
  ["?", "quattrocento", "", ""],
  ["?", "quattrocentosans", "", ""],
  ["?", "questrial", "", ""],
  ["OK", "Quicksand", "https://github.com/andrew-paglinawan/QuicksandFamily.git", "fonts/Quicksand-"],
  ["?", "quintessential", "", ""],
  ["?", "qwigley", "", ""],
  ["?", "racingsansone", "", ""],
  ["?", "radley", "", ""],
  ["?", "rajdhani", "", ""],
  ["OK", "Raleway", "https://github.com/impallari/Raleway.git", "fonts/v3.000 Fontlab/TTF/Raleway-"],
  ["?", "ralewaydots", "", ""],
  ["?", "ralewayvfbeta", "", ""],
  ["UFO", "Ramabhadra", "https://github.com/appajid/ramabhadra", "Ramabhadra"],
  ["UFO", "Ramaraja", "https://github.com/appajid/ramaraja", "Ramaraja-"],
  ["?", "rambla", "", ""],
  ["?", "rammettoone", "", ""],
  ["?", "ranchers", "", ""],
  ["?", "rancho", "", ""],
  ["NOTE", "Ranga", "https://github.com/antonxheight/Ranga", "Ranga-"], # BAD: NON-CANONICAL NAMES.
  ["?", "rationale", "", ""],
  ["UFO", "Raviprakash", "https://github.com/appajid/raviprakash", "RaviPrakash"],
  ["OK", "Redacted", "https://github.com/christiannaths/Redacted-Font.git", "src/Redacted-"],
  ["?", "redactedscript", "", ""],
  ["?", "redressed", "", ""],
  ["?", "reeniebeanie", "", ""],
  ["?", "revalia", "", ""],
  ["OK", "Rhodium Libre", "https://github.com/DunwichType/RhodiumLibre.git", "RhodiumLibre-"],
  ["?", "ribeye", "", ""],
  ["?", "ribeyemarrow", "", ""],
  ["?", "righteous", "", ""],
  ["?", "risque", "", ""],
  ["?", "roboto", "", ""],
  ["?", "robotocondensed", "", ""],
  ["?", "robotomono", "", ""],
  ["?", "robotoslab", "", ""],
  ["?", "rochester", "", ""],
  ["?", "rocksalt", "", ""],
  ["OK", "Rokkitt", "https://github.com/googlefonts/RokkittFont.git", "fonts/TTF/Rokkitt-"],
  ["?", "rokkittvfbeta", "", ""],
  ["?", "romanesco", "", ""],
  ["UFO", "Ropa Sans", "https://github.com/googlefonts/Ropa-Sans.git", "Ropa Sans Adobe L3/FontLab Adobe Latin3/FontLab UFOs/RopaSans-"],
  ["?", "rosario", "", ""],
  ["?", "rosarivo", "", ""],
  ["?", "rougescript", "", ""],
  ["?", "roundedmplus1c", "", ""],
  ["OTF", "Rozhaone", "https://github.com/itfoundry/rozhaone", "build/RozhaOne-"], # sources with OTF binaries, but no TTFs.
  ["OK", "Rubik", "https://github.com/googlefonts/rubik.git", "fonts/ttf/Rubik-"],
  ["?", "rubikmonoone", "", ""],
  ["?", "rubikone", "", ""],
  ["?", "ruda", "", ""],
  ["?", "rufina", "", ""],
  ["?", "rugeboogie", "", ""],
  ["?", "ruluko", "", ""],
  ["?", "rumraisin", "", ""],
  ["?", "ruslandisplay", "", ""],
  ["?", "russoone", "", ""],
  ["?", "ruthie", "", ""],
  ["?", "rye", "", ""],
  ["?", "sacramento", "", ""],
  ["OK", "Sahitya", "https://github.com/juandelperal/sahitya", "ttf/Sahitya-"],
  ["?", "sail", "", ""],
  ["?", "saira", "", ""],
  ["?", "sairacondensed", "", ""],
  ["?", "sairaextracondensed", "", ""],
  ["?", "sairasemicondensed", "", ""],
  ["?", "salsa", "", ""],
  ["?", "sanchez", "", ""],
  ["?", "sancreek", "", ""],
  ["?", "sansation", "", ""],
  ["?", "sansita", "", ""],
  ["?", "sansitaone", "", ""],
  ["?", "sarabun", "", ""],
  ["OK", "Sarala", "https://github.com/huertatipografica/sarala.git", "font/Sarala-"],
  ["?", "sarina", "", ""],
  ["?", "sarpanch", "", ""],
  ["?", "satisfy", "", ""],
  ["?", "sawarabigothic", "", ""],
  ["?", "sawarabimincho", "", ""],
  ["OK", "Scada", "https://github.com/googlefonts/scada.git", "fonts/ttf/Scada-"],
  ["?", "scheherazade", "", ""],
  ["?", "schoolbell", "", ""],
  ["?", "seaweedscript", "", ""],
  ["?", "sedan", "", ""],
  ["?", "sedansc", "", ""],
  ["?", "seoulhangang", "", ""],
  ["?", "seoulhangangcondensed", "", ""],
  ["?", "seoulnamsan", "", ""],
  ["?", "seoulnamsancondensed", "", ""],
  ["?", "seoulnamsanvertical", "", ""],
  ["?", "sevillana", "", ""],
  ["?", "seymourone", "", ""],
  ["?", "shadowsintolight", "", ""],
  ["?", "shadowsintolighttwo", "", ""],
  ["?", "shanti", "", ""],
  ["?", "share", "", ""],
  ["?", "sharetech", "", ""],
  ["?", "sharetechmono", "", ""],
  ["?", "shojumaru", "", ""],
  ["?", "shortstack", "", ""],
  ["?", "siamreap", "", ""],
  ["?", "siemreap", "", ""],
  ["OK", "SigmarOne", "https://github.com/googlefonts/sigmarone.git", "fonts/SigmarOne-"],
  ["?", "signika", "", ""],
  ["?", "signikanegative", "", ""],
##### Not on GFonts:  ["OK", "Silson", "https://github.com/simoncozens/silson", "output/ttf/hinted/SilsonCondensed-"],
  ["?", "simonetta", "", ""],
  ["?", "sintony", "", ""],
  ["?", "sirinstencil", "", ""],
  ["404-ERROR", "Sitara", "https://github.com/Neelakash/sitara", ""],
  ["?", "sixcaps", "", ""],
  ["?", "skranji", "", ""],
  ["?", "slabo13px", "", ""],
  ["?", "slabo27px", "", ""],
  ["NOTE", "Slabo", "https://github.com/TiroTypeworks/Slabo", "TTFs/Slabo"], # BAD: NON-CANONICAL NAMES.
  ["?", "slackey", "", ""],
  ["?", "smokum", "", ""],
  ["?", "smythe", "", ""],
  ["?", "sniglet", "", ""],
  ["?", "snippet", "", ""],
  ["?", "snowburstone", "", ""],
  ["?", "sofadione", "", ""],
  ["?", "sofia", "", ""],
  ["?", "sonsieone", "", ""],
  ["?", "sortsmillgoudy", "", ""],
  ["?", "souliyo", "", ""],
  ["?", "sourcecodepro", "", ""],
  ["?", "sourcesanspro", "", ""],
  ["OK", "Source Serif Pro", "https://github.com/googlefonts/SourceSerifProGFVersion.git", "fonts/SourceSerifPro-"],
  ["OK", "Space Mono", "https://github.com/googlefonts/spacemono.git", "fonts/SpaceMono-"],
  ["?", "specialelite", "", ""],
  ["?", "spicyrice", "", ""],
  ["?", "spinnaker", "", ""],
  ["?", "spirax", "", ""],
  ["?", "squadaone", "", ""],
  ["UFO", "Sreekrushnadevaraya", "https://github.com/appajid/sreekrushnadevaraya", "SreeKrushnadevaraya"],
  ["OK", "Sriracha", "https://github.com/cadsondemak/sriracha.git", "fonts/Sriracha-"],
  ["?", "stalemate", "", ""],
  ["?", "stalinistone", "", ""],
  ["?", "stalinone", "", ""],
  ["?", "stardosstencil", "", ""],
  ["?", "stintultracondensed", "", ""],
  ["?", "stintultraexpanded", "", ""],
  ["?", "stoke", "", ""],
  ["?", "strait", "", ""],
  ["?", "strong", "", ""],
  ["?", "sueellenfrancisco", "", ""],
  ["OK", "Sumana", "https://github.com/cyrealtype/Sumana.git", "Sumana-"],
  ["?", "sunshiney", "", ""],
  ["?", "supermercadoone", "", ""],
  ["OK", "Sura", "https://github.com/huertatipografica/sura.git", "fonts/Sura-"],
  ["UFO", "Suranna", "https://github.com/appajid/suranna", "Suranna"],
  ["UFO", "Suravaram", "https://github.com/appajid/suravaram", "Suravaram"],
  ["?", "suwannaphum", "", ""],
  ["?", "swankyandmoomoo", "", ""],
  ["?", "syncopate", "", ""],
  ["?", "tangerine", "", ""],
  ["?", "taprom", "", ""],
  ["?", "tauri", "", ""],
  ["?", "teko", "", ""],
  ["?", "telex", "", ""],
  ["UFO", "Tenaliramakrishna", "https://github.com/appajid/tenaliramakrishna", "TenaliRamakrishna-"],
  ["?", "tenorsans", "", ""],
  ["?", "terminaldosis", "", ""],
  ["?", "terminaldosislight", "", ""],
  ["?", "textmeone", "", ""],
  ["?", "thabit", "", ""],
  ["?", "tharlon", "", ""],
  ["?", "thegirlnextdoor", "", ""],
  ["?", "tienne", "", ""],
  ["OTF", "Tillana", "https://github.com/itfoundry/tillana", "build/Tillana-"], # sources with OTF binaries, but no TTFs.
  ["NOTE", "Timmana", "https://github.com/appajid/timmana", "TimmanaRegular"], # BAD: NON-CANONICAL NAME.
  ["?", "tinos", "", ""],
  ["?", "titanone", "", ""],
  ["?", "titilliumweb", "", ""],
  ["?", "tradewinds", "", ""],
  ["NOTE", "Trocchi", "https://github.com/vernnobile/TrocchiFont", "Regular/Trocchi"], # BAD: NON-CANONICAL NAME.
  ["?", "trochut", "", ""],
  ["?", "trykker", "", ""],
  ["?", "tuffy", "", ""],
  ["?", "tulpenone", "", ""],
  ["?", "ubuntu", "", ""],
  ["?", "ubuntucondensed", "", ""],
  ["?", "ubuntumono", "", ""],
  ["?", "ultra", "", ""],
  ["?", "uncialantiqua", "", ""],
  ["?", "underdog", "", ""],
  ["?", "unicaone", "", ""],
  ["?", "unifrakturcook", "", ""],
  ["?", "unifrakturmaguntia", "", ""],
  ["?", "unkempt", "", ""],
  ["?", "unlock", "", ""],
  ["?", "unna", "", ""],
  ["?", "vampiroone", "", ""],
  ["?", "varela", "", ""],
  ["OK", "Varela Round Hebrew", "https://github.com/alefalefalef/Varela-Round-Hebrew.git", "fonts/VarelaRound-"],
  ["OK", "Varta", "https://github.com/EbenSorkin/Varta.git", "Varta-"],
  ["?", "vastshadow", "", ""],
  ["OK", "Vesper Libre", "https://github.com/motaitalic/vesper-libre", "VesperLibre-"],
  ["?", "vibur", "", ""],
  ["?", "vidaloka", "", ""],
  ["?", "viga", "", ""],
  ["?", "voces", "", ""],
  ["?", "volkhov", "", ""],
  ["?", "vollkorn", "", ""],
  ["?", "voltaire", "", ""],
  ["?", "vt323", "", ""],
  ["?", "waitingforthesunrise", "", ""],
  ["?", "wallpoet", "", ""],
  ["?", "walterturncoat", "", ""],
  ["?", "warnes", "", ""],
  ["?", "wellfleet", "", ""],
  ["?", "wendyone", "", ""],
  ["?", "wireone", "", ""],
  ["NOTE", "Work Sans", "https://github.com/weiweihuanghuang/Work-Sans", "fonts/webfonts/ttf/WorkSans-"],
  # Note: There's also https://github.com/googlefonts/Work-Sans but the above repo seems more up-to-date.
  ["?", "yaldevicolombo", "", ""],
  ["?", "yanonekaffeesatz", "", ""],
  ["?", "yanonekaffeesatzvfbeta", "", ""],
  ["OTF", "Yantramanav", "https://github.com/erinmclaughlin/Yantramanav", "otf/Yantramanav-"], # sources with OTF binaries, but no TTFs.
  ["?", "yellowtail", "", ""],
  ["?", "yesevaone", "", ""],
  ["?", "yesteryear", "", ""],
  ["?", "yinmar", "", ""],
  ["?", "zeyada", "", ""]
]

if __name__ == '__main__':
  projects_csv = "https://docs.google.com/spreadsheets/d/1ampzD9veEdrwUMkOAJkMNkftqtv1jEygiPR0wZ6eNl8/pub?gid=0&single=true&output=csv"
  cache_csv = "fontprojects.csv"
  import csv
  with open(cache_csv, 'w') as csvfile:
    writer = csv.writer(csvfile, delimiter=' ',
                        quotechar='|', quoting=csv.QUOTE_MINIMAL)
    for repo in git_repos:
      writer.writerow(repo)

  repos_by_status = {}
  for repo in git_repos:
    status = repo[0]
    if status not in repos_by_status.keys():
      repos_by_status[status] = [repo]
    else:
      repos_by_status[status].append(repo)

  total = 0
  enabled = 0
  print ("Number of font repositories in this file:")
  for status in repos_by_status.keys():
    quantity = len(repos_by_status[status])
    print ('"{}": {}'.format(status, quantity))
    total += quantity
    if status in ["OK", "NOTE"]:
      enabled += quantity
  print (('From the total of {} repos,'
          ' {} are enabled.\nEnabled means: "OK" or "NOTE" status.\n').format(total, enabled))
