git_repos = [
  ["Adamina", "https://github.com/cyrealtype/Adamina.git", "fonts/Adamina-"],
  ["Alike", "https://github.com/cyrealtype/Alike.git", "Alike-"],
  ["Amita", "https://github.com/etunni/Amita.git", "TTF/Amita-"],
  ["Arya", "https://github.com/etunni/Arya.git", "TTF/Arya-"],
  ["Asar", "https://github.com/EbenSorkin/Asar.git", "Asar-"],
  ["Atomic Age", "https://github.com/EbenSorkin/Atomic-Age.git", "fonts/ttf/AtomicAge-"],
  ["Basic", "https://github.com/EbenSorkin/Basic.git", "Basic-"],
  ["Bhavuka", "https://github.com/10four/Bhavuka.git", "Bhavuka-"],
  ["Cabin", "https://github.com/impallari/Cabin.git", "fonts/TTF/Cabin-"],
  ["Cambay", "https://github.com/anexasajoop/cambay.git", "cambay/Font files/Unhinted/CambayDevanagari-"],
  ["Chonburi", "https://github.com/cadsondemak/chonburi.git", "fonts/Chonburi-"],
  ["Cormorant", "https://github.com/CatharsisFonts/Cormorant.git", "1. TrueType Font Files/Cormorant-"],
  ["Dekko", "https://github.com/EbenSorkin/Dekko.git", "Dekko-"],
  ["Federant", "https://github.com/cyrealtype/Federant.git", "Federant-"],
  ["Glegoo", "https://github.com/etunni/glegoo.git", "Glegoo-"],
  ["Homenaje", "https://github.com/googlefonts/Homenaje.git", "fonts/Homenaje-"],
  #{"Inconsolata", "https://github.com/google/fonts/tree/master/ofl/inconsolata", ""},
  ["Inknut Antiqua", "https://github.com/clauseggers/Inknut-Antiqua.git", "TTF-OTF/InknutAntiqua-"],
  ["Itim", "https://github.com/cadsondemak/itim.git", "fonts/Itim-"],
  ["Kanit", "https://github.com/cadsondemak/kanit.git", "font/Kanit-"],
  ["Kavoon", "https://github.com/EbenSorkin/Kavoon.git", "Kavoon-"],
  ["Khula", "https://github.com/erinmclaughlin/Khula.git", "ttf_hinted/Khula-"],
  ["Kurale", "https://github.com/etunni/kurale.git", "fonts/Kurale-"],
  ["Lato", "https://github.com/googlefonts/LatoGFVersion.git", "fonts/Lato-"],
  ["Poiret One", "https://github.com/alexeiva/poiretone.git", "fonts/ttf/PoiretOne-"],
  ["Quicksand", "https://github.com/andrew-paglinawan/QuicksandFamily.git", "fonts/Quicksand-"],
  ["Raleway", "https://github.com/impallari/Raleway.git", "fonts/v3.000 Fontlab/TTF/Raleway-"]
  ["Redacted", "https://github.com/christiannaths/Redacted-Font.git", "src/Redacted-"],
  ["Rhodium Libre", "https://github.com/DunwichType/RhodiumLibre.git", "RhodiumLibre-"],
  ["Sarala", "https://github.com/huertatipografica/sarala.git", "font/Sarala-"],
  ["Sriracha", "https://github.com/cadsondemak/sriracha.git", "fonts/Sriracha-"],
  ["Sumana", "https://github.com/cyrealtype/Sumana.git", "Sumana-"],
  ["Sura", "https://github.com/huertatipografica/sura.git", "fonts/Sura-"],
  ["Varela Round", "https://github.com/alefalefalef/Varela-Round-Hebrew.git", "fonts/VarelaRound-"],
  ["Varta", "https://github.com/EbenSorkin/Varta.git", "Varta-"],
]

