#!/usr/bin/env python
git_repos = [
  ["Adamina", "https://github.com/cyrealtype/Adamina.git", "fonts/Adamina-"],
  #["Abhaya Libre", "https://github.com/mooniak/abhaya-libre-font", ""],
  #["Adobe Blank", "https://github.com/adobe-fonts/adobe-blank", ""],
  #["Anaheim", "https://github.com/vernnobile/anaheimFont", ""],
  ["Alike", "https://github.com/cyrealtype/Alike.git", "Alike-"],
  ["Amita", "https://github.com/etunni/Amita.git", "TTF/Amita-"],
  ["Arya", "https://github.com/etunni/Arya.git", "TTF/Arya-"],
  ["Asar", "https://github.com/EbenSorkin/Asar.git", "Asar-"],
  ["Atomic Age", "https://github.com/EbenSorkin/Atomic-Age.git", "fonts/ttf/AtomicAge-"],
  #["Biryani", "https://github.com/typeoff/biryani", ""],
  #["Baloo", "https://github.com/girish-dalvi/Baloo", ""],
  ["Basic", "https://github.com/EbenSorkin/Basic.git", "Basic-"],
  ["Bhavuka", "https://github.com/10four/Bhavuka.git", "Bhavuka-"],
  ["Cabin", "https://github.com/impallari/Cabin.git", "fonts/TTF/Cabin-"],
  ["Cambay", "https://github.com/anexasajoop/cambay.git", "cambay/Font files/Unhinted/CambayDevanagari-"],
  #["Catamaran", "https://github.com/VanillaandCream/Catamaran", ""],
  ["Chonburi", "https://github.com/cadsondemak/chonburi.git", "fonts/Chonburi-"],
  #["Coda", "https://github.com/vernnobile/CodaFont", ""],
  ["Cormorant", "https://github.com/CatharsisFonts/Cormorant.git", "1. TrueType Font Files/Cormorant-"],
  #["Cutive", "https://github.com/vernnobile/Cutive", ""],
  ### duplicate? ==> ["CutiveFont", "https://github.com/vernnobile/CutiveFont", ""],
  #["Datalegreya", "https://github.com/figs-lab/datalegreya", ""],
  ["Dekko", "https://github.com/EbenSorkin/Dekko.git", "Dekko-"],
  #["Dhurjati", "https://github.com/appajid/dhurjati", ""],
  #["Dhyana", "https://github.com/vernnobile/DhyanaFont", ""],
  #["Digital Numbers", "https://github.com/s-a/digital-numbers-font", ""],
  #["Dinah", "https://github.com/elms-/Dinah", ""],
  #["Eczar", "https://github.com/rosettatype/Eczar", ""],
  #["Ek-Mukta", "https://github.com/girish-dalvi/Ek-Mukta", ""],
  ["Federant", "https://github.com/cyrealtype/Federant.git", "Federant-"],
  #["Fira", "https://github.com/mozilla/Fira", ""],
  #["Fruktur", "https://github.com/EbenSorkin/Fruktur", ""],
  #["Gidugu", "https://github.com/appajid/gidugu", ""],
  ["Glegoo", "https://github.com/etunni/glegoo.git", "Glegoo-"],
  #["Gurajada", "https://github.com/appajid/gurajada", ""],
  #["Hind Colombo", "https://github.com/itfoundry/hind-colombo", ""],
  #["Hind Guntur", "https://github.com/itfoundry/hind-guntur", ""],
  #["Hind Jalandhar", "https://github.com/itfoundry/hind-jalandhar", ""],
  #["Hind Kochi", "https://github.com/itfoundry/hind-kochi", ""],
  #["Hind Madurai", "https://github.com/itfoundry/hind-madurai", ""],
  #["Hind Mysuru", "https://github.com/itfoundry/hind-mysuru", ""],
  #["Hind Siliguri", "https://github.com/itfoundry/hind-siliguri", ""],
  #["Hind Vadodara", "https://github.com/itfoundry/hind-vadodara", ""],
  ["Homenaje", "https://github.com/googlefonts/Homenaje.git", "fonts/Homenaje-"],
  #{"Inconsolata", "https://github.com/google/fonts/tree/master/ofl/inconsolata", ""},
  ["Inknut Antiqua", "https://github.com/clauseggers/Inknut-Antiqua.git", "TTF-OTF/InknutAntiqua-"],
  ["Itim", "https://github.com/cadsondemak/itim.git", "fonts/Itim-"],
  #["Jaldi", "https://github.com/Omnibus-Type/Jaldi", ""],
  #["Jura", "https://github.com/ossobuffo/jura", ""],
  #["Kadwa", "https://github.com/solmatas/Kadwa", ""],
  #["Kalam", "https://github.com/itfoundry/kalam", ""],
  ["Kanit", "https://github.com/cadsondemak/kanit.git", "font/Kanit-"],
  ["Kavoon", "https://github.com/EbenSorkin/Kavoon.git", "Kavoon-"],
  #["Khand", "https://github.com/itfoundry/khand", ""],
  ["Khula", "https://github.com/erinmclaughlin/Khula.git", "ttf_hinted/Khula-"],
  ["Kurale", "https://github.com/etunni/kurale.git", "fonts/Kurale-"],
  ["Lato", "https://github.com/googlefonts/LatoGFVersion.git", "fonts/Lato-"],
  #["Lakkireddy", "https://github.com/appajid/lakkireddy", ""],
  #["Mallanna", "https://github.com/appajid/mallanna", ""],
  #["Mandali", "https://github.com/appajid/mandali", ""],
  #["Martel", "https://github.com/typeoff/martel", ""],
  #["Martel Sans", "https://github.com/typeoff/martel_sans", ""],
  #["Merriweather Sans", "https://github.com/EbenSorkin/Merriweather-Sans", ""],
  #["Modak", "https://github.com/girish-dalvi/Modak", ""],
  #["Monda", "https://github.com/vernnobile/mondaFont", ""],
  #["Nats", "https://github.com/appajid/nats", ""],
  #["Ntr", "https://github.com/appajid/ntr", ""],
  #["Padauk", "https://github.com/silnrsi/font-padauk", ""],
  #["Palanquin", "https://github.com/VanillaandCream/Palanquin", ""],
  #["Peddana", "https://github.com/appajid/peddana", ""],
  ["Poiret One", "https://github.com/alexeiva/poiretone.git", "fonts/ttf/PoiretOne-"],
  #["Ponnala", "https://github.com/appajid/ponnala", ""],
  #["Poppins", "https://github.com/itfoundry/poppins", ""],
  #["Pragati Narrow", "https://github.com/Omnibus-Type/PragatiNarrow", ""],
  ["Quicksand", "https://github.com/andrew-paglinawan/QuicksandFamily.git", "fonts/Quicksand-"],
  ["Raleway", "https://github.com/impallari/Raleway.git", "fonts/v3.000 Fontlab/TTF/Raleway-"],
  #["Ranga", "https://github.com/antonxheight/Ranga", ""],
  #["Ramabhadra", "https://github.com/appajid/ramabhadra", ""],
  #["Ramaraja", "https://github.com/appajid/ramaraja", ""],
  #["Raviprakash", "https://github.com/appajid/raviprakash", ""],
  ["Redacted", "https://github.com/christiannaths/Redacted-Font.git", "src/Redacted-"],
  ["Rhodium Libre", "https://github.com/DunwichType/RhodiumLibre.git", "RhodiumLibre-"],
  #["Rozhaone", "https://github.com/itfoundry/rozhaone", ""],
  #["Sahitya", "https://github.com/juandelperal/sahitya", ""],
  ["Sarala", "https://github.com/huertatipografica/sarala.git", "font/Sarala-"],
  #["Silson", "https://github.com/simoncozens/silson", ""],
  #["Sitara", "https://github.com/Neelakash/sitara", ""],
  #["Slabo", "https://github.com/TiroTypeworks/Slabo", ""],
  #["Source Serif Pro", "https://github.com/adobe/source-serif-pro", ""],
  #["Sreekrushnadevaraya", "https://github.com/appajid/sreekrushnadevaraya", ""],
  ["Sriracha", "https://github.com/cadsondemak/sriracha.git", "fonts/Sriracha-"],
  ["Sumana", "https://github.com/cyrealtype/Sumana.git", "Sumana-"],
  ["Sura", "https://github.com/huertatipografica/sura.git", "fonts/Sura-"],
  #["Suranna", "https://github.com/appajid/suranna", ""],
  #["Suravaram", "https://github.com/appajid/suravaram", ""],
  #["Tenaliramakrishna", "https://github.com/appajid/tenaliramakrishna", ""],
  #["Tillana", "https://github.com/itfoundry/tillana", ""],
  #["Timmana", "https://github.com/appajid/timmana", ""],
  #["TrocchiFont", "https://github.com/vernnobile/TrocchiFont", ""],
  ["Varela Round Hebrew", "https://github.com/alefalefalef/Varela-Round-Hebrew.git", "fonts/VarelaRound-"],
  ["Varta", "https://github.com/EbenSorkin/Varta.git", "Varta-"],
  #["Vesper Libre", "https://github.com/motaitalic/vesper-libre", ""],
  #["Work Sans", "https://github.com/weiweihuanghuang/Work-Sans", ""],
  #["Yantramanav", "https://github.com/erinmclaughlin/Yantramanav", ""]
]

if __name__ == '__main__':
  print ("There are {} font repositories listed in this file.".format(len(git_repos)))
