PROFILE = {
    "include_profiles": ["universal"],
    "pending_review": [
        "opentype:weight_class_fvar",
        "opentype:slant_direction",
        "cmap/format_12",
        "color_cpal_brightness",
        "colorfont_tables",
        "empty_letters",
        "family/control_chars",
        "file_size",
        "fvar_name_entries",
        "fontdata_namecheck",
        "glyf_nested_components",
        "hinting_impact",
        "inconsistencies_between_fvar_stat",
        "kerning_for_non_ligated_sequences",
        "ligature_carets",
        "mandatory_avar_table",
        "missing_small_caps_glyphs",
        "name/family_and_style_max_length",
        "no_mac_entries",
        "render_own_name",
        "smart_dropout",
        "stylisticset_description",
        "typographic_family_name",
        "varfont/consistent_axes",
        "vtt_volt_data",  # very similar to vttclean, may be a good idea to merge them.
        "vttclean",
    ],
    "sections": {
        "Font Bureau Checks": [
            "fontbureau:ytlc_sanity",
        ],
    },
}
