PROFILE = {
    "sections": {
        "Metadata Checks": [
            "microsoft:copyright",
            "microsoft:fstype",
            "microsoft:license_description",
            "microsoft:manufacturer",
            "microsoft:trademark",
            "microsoft:vendor_url",
            "microsoft:version",
        ],
        "Name Checks": [
            "microsoft:office_ribz_req",
            "microsoft:typographic_family_name",
            #
            "name_id_1",
            "name_id_2",
            "name_length_req",
        ],
        "Metrics Checks": [
            "microsoft:vertical_metrics",
        ],
        "Variable Fonts Checks": [
            "microsoft:fvar_STAT_axis_ranges",
            "microsoft:STAT_axis_values",
            "microsoft:STAT_table_axis_order",
            "microsoft:STAT_table_eliding_bit",
        ],
        "Sanity Checks": [
            "vtt_volt_data",
        ],
        "Glyph Checks": [
            "tnum_glyphs_equal_widths",
        ],
        "Superfamily Checks": [
            "superfamily/list",
            "superfamily/vertical_metrics",
        ],
        "Universal Profile Checks": [
            "alt_caron",
            "arabic_high_hamza",
            "arabic_spacing_symbols",
            "case_mapping",
            "cjk_chws_feature",
            "contour_count",
            "family/single_directory",
            "family/vertical_metrics",
            "family/win_ascent_and_descent",
            # "fontbakery_version",  # We update at our own pace
            "freetype_rasterizer",
            "gpos7",
            "interpolation_issues",
            "legacy_accents",
            "linegaps",
            "mandatory_glyphs",
            "math_signs_width",
            "name/trailing_spaces",
            "os2_metrics_match_hhea",
            "ots",
            "required_tables",
            "rupee",
            "sfnt_version",
            "soft_hyphen",
            # "STAT_in_statics",  # Difference of opinion
            "STAT_strings",
            # "tabular_kerning",  # We have tnum_glyphs_equal_widths
            "transformed_components",
            "ttx_roundtrip",
            "unique_glyphnames",
            "unreachable_glyphs",
            "unwanted_tables",
            "valid_glyphnames",
            "whitespace_glyphnames",
            "whitespace_glyphs",
            "whitespace_ink",
            "whitespace_widths",
        ],
        "OpenType Specification Checks": [
            "opentype:caret_slope",
            "opentype:cff2_call_depth",
            "opentype:cff_call_depth",
            "opentype:cff_deprecated_operators",
            "opentype:code_pages",
            "opentype:dsig",
            "opentype:family/bold_italic_unique_for_nameid1",
            "opentype:family/consistent_family_name",
            "opentype:family/equal_font_versions",
            "opentype:family/max_4_fonts_per_family_name",
            "opentype:family_naming_recommendations",
            "opentype:family/panose_familytype",
            "opentype:family/underline_thickness",
            "opentype:font_version",
            "opentype:fsselection",
            "opentype:fsselection_matches_macstyle",
            "opentype:gdef_mark_chars",
            "opentype:gdef_non_mark_chars",
            "opentype:gdef_spacing_marks",
            "opentype:glyf_non_transformed_duplicate_components",
            "opentype:glyf_unused_data",
            "opentype:gpos_kerning_info",
            "opentype:italic_angle",
            "opentype:italic_axis_in_stat",
            "opentype:italic_axis_in_stat_is_boolean",
            "opentype:italic_axis_last",
            "opentype:kern_table",
            "opentype:layout_valid_feature_tags",
            "opentype:layout_valid_language_tags",
            "opentype:layout_valid_script_tags",
            "opentype:loca/maxp_num_glyphs",
            "opentype:mac_style",
            "opentype:maxadvancewidth",
            "opentype:monospace",
            "opentype:name/empty_records",
            "opentype:name/italic_names",
            "opentype:name/match_familyname_fullfont",
            "opentype:name/no_copyright_on_description",
            "opentype:name/postscript_name_consistency",
            "opentype:name/postscript_vs_cff",
            "opentype:points_out_of_bounds",
            "opentype:postscript_name",
            "opentype:post_table_version",
            "opentype:stat_has_axis_value_tables",
            "opentype:unitsperem",
            "opentype:varfont/distinct_instance_records",
            "opentype:varfont/family_axis_ranges",
            "opentype:varfont/foundry_defined_tag_name",
            "opentype:varfont/ital_range",
            "opentype:varfont/regular_ital_coord",
            "opentype:varfont/regular_opsz_coord",
            "opentype:varfont/regular_slnt_coord",
            "opentype:varfont/regular_wdth_coord",
            "opentype:varfont/regular_wght_coord",
            "opentype:varfont/same_size_instance_records",
            "opentype:varfont/slnt_range",
            "opentype:varfont/stat_axis_record_for_each_axis",
            "opentype:varfont/valid_axis_nameid",
            "opentype:varfont/valid_default_instance_nameids",
            "opentype:varfont/valid_postscript_nameid",
            "opentype:varfont/valid_subfamily_nameid",
            "opentype:varfont/wdth_valid_range",
            "opentype:varfont/wght_valid_range",
            "opentype:vendor_id",
            "opentype:xavgcharwidth",
        ],
    },
}
