name: Tests & linting with tox

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install FontValidator (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install mono-runtime libmono-system-windows-forms4.0-cil
        wget https://github.com/HinTak/Font-Validator/releases/download/FontVal-2.1.2/FontVal-2.1.2-ubuntu-16.04-x64.tgz
        tar -xvzf ./FontVal-2.1.2-ubuntu-16.04-x64.tgz
        sudo mv ./FontVal-2.1.2-ubuntu-16.04-x64/FontValidator /usr/local/bin/FontValidator

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox
